### ISSUE TITLE
ambiguous indirect export: getLanguage

### ISSUE THREAD

**Issue by Shahryar1991** [Bas950/Language-Flag-Colors#16]
Hi
Sorry to bring this up again. This time I've a new error message and it say `ambiguous indirect export: getLanguage`.
![image](https://user-images.githubusercontent.com/11885343/188471269-6375662e-9034-42b9-9532-7747f6c91dfb.png)
I'm using these dependencies:

"dependencies": {
    "@chenfengyuan/vue-countdown": "^2.1.0",
    "@headlessui/vue": "^1.6.7",
    "@heroicons/vue": "^2.0.10",
    "@tinymce/tinymce-vue": "^5.0.0",
    "autoprefixer": "^10.4.8",
    "axios": "^0.27.2",
    "country-flag-emoji": "^1.0.3",
    "crypto-js": "^4.1.1",
    "cssnano": "^5.1.13",
    "firebase": "^9.9.3",
    "highcharts-vue": "^1.4.0",
    "jalali-moment": "^3.3.11",
    "language-flag-colors": "^2.1.1",
    "moment-jalaali": "^0.9.6",
    "postcss": "^8.4.16",
    "postcss-import": "^15.0.0",
    "sass": "^1.54.7",
    "tailwindcss-rtl": "^0.9.0",
    "tinymce": "^6.1.2",
    "tinymce-i18n": "^22.8.26",
    "uuid": "^8.3.2",
    "vue": "^3.2.37",
    "vue-gtag": "^2.0.1",
    "vue-router": "^4.1.5",
    "vuefire": "^2.2.5",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@tailwindcss/forms": "^0.5.2",
    "@vitejs/plugin-vue": "^3.0.1",
    "tailwindcss": "^3.1.8",
    "vite": "^3.1.0"
  }

my code:
`import languages, { getLanguage } from "language-flag-colors";`
`console.log(languages, getLanguage("pt"))`

![image](https://user-images.githubusercontent.com/11885343/188472215-6de08c4d-388f-4c8c-8b73-2e64da2ad48e.png)

**Comment by ImRodry** [comment]
You’re not giving us much to work with. Where did you get this error? What did you do to get it? Why the hell do you have vite as a dependency? Why do you have country-flag-emoji as a dependency?

**Comment by Shahryar1991** [comment]
Please check out this project:
https://github.com/Shahryar1991/vue-project

I used country-flag-emoji for testing. I'll remove that from my project.

I think this way is better to see what is wrong with my project.

**Comment by ImRodry** [comment]
@Shahryar1991 not sure if your issue is related to ESM but if it is, could you try updating to the latest version to see if it fixes it?
